name: readerapp_design
description: "readerapp"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/Hownottodiealone.png
    - lib/assets/the_power.jpeg
    - lib/assets/nolonger.jpg
    - lib/assets/atomic.png
    - lib/assets/educated.jpg
    - lib/assets/sapiens.png

 